train_transforms:
  - name: Resize
    params:
      size: [256, 256]

  - name: RandomHorizontalFlip
    params:
      p: 0.5

  - name: ToTensor
    params: {}

  - name: Normalize
    params:
      mean: [0.485, 0.456, 0.406]
      std:  [0.229, 0.224, 0.225]

test_transforms:
  - name: Resize
    params:
      size: [256, 256]

  - name: ToTensor
    params: {}

  - name: Normalize
    params:
      mean: [0.485, 0.456, 0.406]
      std:  [0.229, 0.224, 0.225]
  
# base model configurations
base_model_config:
  base_model_name: vgg16
  base_model_weights: IMAGENET1K_V1

# updated base model configurations
updated_model_config:
  num_classes: 2
  unfreeze_last_n_conv: 1
  unfreeze_last_n_fc: 3
  dropout_rate: 0.5 
  use_batch_norm: false
   